// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.13 1.gltf 
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei/native'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/1.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} rotation={[-Math.PI / 2, 0, 0]} />
//     </group>
//   )
// }

// useGLTF.preload('/1.gltf')
